// Product data is now using local public images

export type Product = {
  id: string;
  name: string;
  tamil?: string;
  category: string;
  priceUSD: number; // per Kg, mid-range
  priceRange?: string; // e.g. "0.48 - 0.96"
  image: string;
  description: string;
};

export const PRODUCTS: Product[] = [
  { id: "avuri", name: "Premium Senna Leaves (Avuri) - Sun Dried", category: "Leaves", priceUSD: 12.99, priceRange: "11.50 - 14.50", image: "/products/WhatsApp Image 2026-06-09 at 3.38.41 PM (1).jpeg", description: "Grade-A Senna leaves sourced from the arid regions of Tirunelveli. Rich in sennosides, naturally processed to preserve its gentle digestive cleansing properties. Perfect for herbal tea blends." },
  { id: "moringa-leaves", name: "Wild-Harvested Moringa Oleifera Leaves", category: "Leaves", priceUSD: 19.50, priceRange: "17.00 - 22.00", image: "/products/WhatsApp Image 2026-06-09 at 3.38.45 PM (1).jpeg", description: "Superfood grade Moringa leaves, triple-washed and shade-dried to retain vibrant green color and high nutrient density. Contains 90+ nutrients and 46 antioxidants." },
  { id: "thuthi", name: "Kalachikai Premium Seeds", category: "Seeds", priceUSD: 11.99, priceRange: "10.50 - 13.50", image: "/products/WhatsApp Image 2026-06-09 at 3.38.42 PM (1).jpeg", description: "Premium whole Caesalpinia Bonduc seeds, meticulously sourced for their therapeutic potency. Renowned in traditional Siddha and Ayurvedic medicine for supporting hormonal balance (PCOS support) and metabolic health. Triple-graded to ensure the highest purity and bioactive content." },
  { id: "flex-seed", name: "Arasa Vidhai powder / Peepal / Aswatha seeds", category: "Seeds", priceUSD: 16.20, priceRange: "14.50 - 18.00", image: "/products/WhatsApp Image 2026-06-09 at 3.38.42 PM.jpeg", description: "Pure ground Arasa Vidhai (Peepal seeds), highly valued in Ayurveda for supporting reproductive health, hormonal balance, and overall vitality. Naturally processed to preserve its bioactive compounds." },
  { id: "sathakuppai", name: "Organic Thuthi Leaves (Abutilon Indicum)", category: "Leaves", priceUSD: 11.99, priceRange: "10.50 - 13.50", image: "/products/WhatsApp Image 2026-06-09 at 3.38.45 PM (2).jpeg", description: "Premium Organic Thuthi leaves, also known as Indian Mallow. Highly valued in Siddha medicine for its soothing and anti-inflammatory properties. Traditionally used for hemorrhoid (piles) relief, digestive health, and respiratory support." },
  { id: "vasambu", name: "Hand-Graded Vasambu (Sweet Flag) Rhizome", category: "Roots", priceUSD: 24.99, priceRange: "21.50 - 28.50", image: "/products/WhatsApp Image 2026-06-09 at 3.38.46 PM (2).jpeg", description: "Aged Sweet Flag rhizomes, carefully sliced and dried. Known for its distinct woody aroma and traditional use in boosting immunity and digestive health in infants." },
  { id: "marikolunthu", name: "Flax seed", category: "Seeds", priceUSD: 18.80, priceRange: "16.50 - 21.00", image: "/products/WhatsApp Image 2026-06-09 at 3.38.46 PM.jpeg", description: "Premium triple-cleaned brown flax seeds, rich in Omega-3 fatty acids, dietary fiber, and lignans. Ideal for supporting heart health, digestive wellness, and as a nutrient-dense addition to daily diets." },
  { id: "vettiver", name: "Premium Vettiver (Khus) Roots - Cooling Grade", category: "Roots", priceUSD: 31.50, priceRange: "28.00 - 35.00", image: "/products/WhatsApp Image 2026-06-09 at 3.38.41 PM.jpeg", description: "Deep-earth Vetiver roots, intensely fragrant. Naturally cooling and grounding. Ideal for making traditional cooling screens, root-infused water, and aromatherapy extracts." },
  { id: "vallarai", name: "Sana patti Senna Leaves", category: "Leaves", priceUSD: 19.50, priceRange: "17.00 - 22.00", image: "/products/WhatsApp Image 2026-06-09 at 3.38.45 PM.jpeg", description: "Premium dried Cassia angustifolia leaves, traditionally known as Sana Patti. Highly recognized in Ayurvedic medicine for its natural laxative and detoxifying properties. Expertly harvested and shade-dried to maintain peak sennoside content for digestive wellness." },
  { id: "poolankilangu", name: "Dried Drumstick Flowers", category: "Flowers", priceUSD: 31.00, priceRange: "28.00 - 35.00", image: "/products/WhatsApp Image 2026-06-09 at 3.38.44 PM (2).jpeg", description: "Premium, shade-dried Moringa oleifera blossoms. Often called a hidden superfood, these delicate petals are rich in Vitamin C, potassium, and antioxidants. Traditionally used for immune support, reducing body heat, and enhancing metabolic wellness." },
  { id: "kalachikai", name: "Rare White Turmeric (Poolankilangu) Roots", category: "Roots", priceUSD: 19.99, priceRange: "17.50 - 22.50", image: "/products/WhatsApp Image 2026-06-09 at 3.38.41 PM (2).jpeg", description: "Premium Curcuma zedoaria rhizomes. Renowned for their floral-mango aroma and skin-brightening properties. Unlike yellow turmeric, it doesn't stain. A staple in traditional Ayurvedic beauty rituals for acne control, evening skin tone, and deep detoxification." },
  { id: "rose-petal", name: "Dried Damask Rose Petals - Culinary Grade", category: "Flowers", priceUSD: 34.50, priceRange: "30.00 - 40.00", image: "/products/WhatsApp Image 2026-06-09 at 3.38.42 PM (2).jpeg", description: "Fragrant sun-dried Damask petals. Retains natural oils and crimson hue. Edible grade, perfect for gourmet tea, herbal infusions, desserts, and organic skincare formulations." },
  { id: "karpoga-arisi", name: "Karpoga Arisi (Bavanchi) - Purity Guaranteed", category: "Seeds", priceUSD: 18.40, priceRange: "16.00 - 21.50", image: "/products/WhatsApp Image 2026-06-09 at 3.38.43 PM.jpeg", description: "Premium Psoralea Corylifolia seeds. Highly valued for supporting healthy skin pigmentation and dermatological wellness. Sourced from organic-certified farms." },
  { id: "moringa-seed", name: "Moringa Oleifera PKM-1 Transformation Seeds", category: "Seeds", priceUSD: 38.00, priceRange: "34.00 - 42.00", image: "/products/WhatsApp Image 2026-06-09 at 3.38.43 PM (1).jpeg", description: "High-germination PKM-1 variety seeds. Dual purpose: ideal for establishing high-yield plantations or for natural water flocculation and clarification applications." },
  { id: "ashwagandha", name: "Premium Ashwagandha (Amukkiran) Roots", category: "Roots", priceUSD: 42.50, priceRange: "38.50 - 48.00", image: "/products/WhatsApp Image 2026-06-09 at 3.38.46 PM (3).jpeg", description: "Select-grade Withania Somnifera roots. Harvested at peak maturity to ensure maximum withanolide concentration. The ultimate adaptogen for stress management and vitality." },
  { id: "hibiscus", name: "Whole Dried Red Hibiscus Rosa-Sinensis Flowers", category: "Flowers", priceUSD: 28.80, priceRange: "25.00 - 32.50", image: "/products/WhatsApp Image 2026-06-09 at 3.38.44 PM.jpeg", description: "Botonically pure dried hibiscus blossoms. Rich in Vitamin C and AHA acids. Perfect for strengthening hair follicles or brewing vibrant, antioxidant-rich ruby herbal tea." },
  { id: "kanda-thippili", name: "Premium Kanda Thippili (Long Pepper) Catkins", category: "Spices", priceUSD: 44.00, priceRange: "40.00 - 48.00", image: "/products/WhatsApp Image 2026-06-09 at 3.38.44 PM (1).jpeg", description: "High-pungency Piper Longum spikes. Expertly harvested and sun-cured. Known for its powerful bio-enhancing properties and use in traditional digestive and respiratory tonics." },
  { id: "moringa-flower", name: "Delicate Organic Moringa Flowers (Dried)", category: "Flowers", priceUSD: 31.00, priceRange: "28.00 - 35.00", image: "/products/WhatsApp Image 2026-06-09 at 3.38.43 PM (2).jpeg", description: "Rare dried moringa blossoms. A subtle, honey-like aroma with potent health benefits. Rich in potassium and calcium. A unique addition to nutritional wellness products." },
];


export const CATEGORIES = ["All", "Leaves", "Seeds", "Roots", "Flowers", "Spices"] as const;
